#!/bin/bash

# Figures in the PLOTTING MACHINE!
#
# 0 - Convert all eps to pdf
# 1 - Noise comparison analytic/simulation
# 2 - Power spectra plot.
# 3 - Power spectra plot with inset.
# 4 - Potentially difference between Gasper and Joris
# 5 - Tablaux for saturation vs correlation time
# 6 - Pbound with a sink
# 7 - Plot of S(t|eq) and S(t|\sigma), timescale seperation.
# 8 - Comparing rdens plots between newBD2D and GF'n 2DRadInf.

plot=$1

prefix1="/usr/share/texmf-texlive/fonts/type1/bluesky/cm"
prefix2="/usr/share/texmf-texlive/fonts/type1/public/amsfonts/cm"

fontfile1="$prefix1/cmmib10.pfb"
fontfile2="$prefix1/cmti12.pfb"
fontfile3="$prefix1/cmbx12.pfb"

lines1=\
"
set style line 1 ps 1 pt 7 lt 1 lc rgb 'gray10'
set style line 2 ps 1 pt 6 lt 1 lc rgb 'gray30'
set style line 3 ps 1 pt 7 lt 1 lc rgb 'gray50'
set style line 4 ps 1 pt 6 lt 1 lc rgb 'gray70'
set style line 5 ps 1 pt 7 lt 1 lc rgb 'gray90'
set style line 6 ps 1 pt 7 lt 1 lc rgb '#FF0000'
set style line 7 ps 1 pt 6 lt 1 lc rgb '#FF040E'
set style line 8 ps 1 pt 7 lt 1 lc rgb '#FF6868'
set style line 9 ps 0.4 pt 6 lt 1 lc rgb '#FFA9A5'
set style line 10 ps 1 pt 7 lt 1 lc rgb '#FFE9E5'
"

lines2=\
"
set style line 11 lw 2 lt 1 lc rgb 'gray10'
set style line 12 lw 2 lt 2 lc rgb 'gray30'
set style line 13 lw 2 lt 1 lc rgb 'gray50'
set style line 14 lw 2 lt 2 lc rgb 'gray70'
set style line 15 lw 2 lt 1 lc rgb 'gray90'
set style line 16 lw 4 lt 1 lc rgb '#FF0000'
set style line 17 lw 2 lt 2 lc rgb '#FF040E'
set style line 18 lw 2 lt 1 lc rgb '#006868'
set style line 19 lw 4 lt 2 lc rgb '#68FFAA'
set style line 20 lw 2 lt 1 lc rgb '#FFE9E5'
"

lines3=\
"
set style line 1 lw 4 lt 1 lc rgb '#CC5555'
set style line 2 lw 4 lt 2 lc rgb '#55CC55'
set style line 3 lw 4 lt 3 lc rgb '#5555CC'
set style line 4 lw 4 lt 4 lc rgb '#CC55CC'
set style line 5 lw 2 lt 2 lc rgb 'gray10'
set style line 6 lw 2 lt 4 lc rgb 'gray50'
set style line 7 lw 2 lt 1 lc rgb '#FF040E'
set style line 8 lw 2 lt 1 lc rgb '#006868'
set style line 9 lw 4 lt 1 lc rgb '#68FFAA'
set style line 10 lw 2 lt 4 lc rgb 'gray50'
"

# Linetype library:
# 1 - solid line __________
# 2 - dashed as __ __ __ __
# 3 - dashed as _ _ _ _ _ _
# 4 - dashed as ...........
# 5 - dashed as __.__.__.__
# 6 - dashed as _._._._._._

#Convert all eps formats to pdf not done by gnuplot
if [[ $plot -eq 0 ]]
then

epstopdf Sink_domain.eps
epstopdf promoter_schematic.eps

epstopdf gfrd_single.eps
epstopdf gfrd_pair.eps
epstopdf gfrd_domain.eps
epstopdf gfrd_domain2.eps

fi



#Noise comparison analytic/simulation
if [[ $plot -eq 1 ]]
then

$lines1
$lines2

gnuplot << EOF -persist

set terminal postscript eps enhanced color
set out "NoisePlotFull.eps"

#$lines2

#set yrange [-2:2]
set xrange [0:1]

#set ytics 2 format "%g"
#set xtics 2 format "%g"
set xlabel "n"
set ylabel "P_{n}(0)"
#set key outside Left samplen 1 spacing 1.2 width -0.5

#set arrow nohead from -6,0 to 0,0 ls 14

#plot "./Results.dat"
plot "./NoiseResult.dat" using 2:4:(sqrt(\$3)):(sqrt(\$5)) with xyerrorbars ls 18 title "Simulated",\
"./NoisePlotJ_ana.dat" with lines ls 16 notitle,\
"./NoisePlotB_ana.dat" with lines ls 13 title "Analytical Gasper"
#"./Result.dat" using 2:4 with lines notitle,\
#"./RecAverage.dat" using 2:(10*\$4):(sqrt(\$3)):(10*sqrt(\$5)) with xyerrorbars notitle

EOF

epstopdf NoisePlotFull.eps
fi


#Power spectra plot.
if [[ $plot -eq 2 ]]
then

gnuplot << EOF -persist

$lines1
$lines2

set terminal postscript eps enhanced color
set out "PowerPlot.eps"

set log xy

#set yrange [-2:2]
#set xrange [0:1]

#set ytics 2 format "%g"
#set xtics 2 format "%g"
set xlabel "{/Symbol w}"
set ylabel "P_{n}({/Symbol w})"
set rmargin 4
#set key outside Left samplen 1 spacing 1.2 width -0.5

#set arrow nohead from -6,0 to 0,0 ls 14

plot "./PowerPlotExt_ana.dat" with lines ls 16 title "Extrinsic analytical",\
"./PowerPlotInt_ana.dat" with lines ls 19 title "Intrinsic analytical",\
"./PowerPlotTot_sim.dat" with lines ls 11 title "Simulated"

EOF

epstopdf PowerPlot.eps
fi






#Power spectra plot with inset.
if [[ $plot -eq 3 ]]
then

gnuplot << EOF -persist

$lines1
$lines2

set terminal postscript eps enhanced color
set out "PowerPlot2.eps"

set size 1,1
set origin 0,0
#set nokey
set multiplot

set log xy

set size 1,1
set origin 0,0

set format y "10^{%L}"
set format x "10^{%L}"

#set yrange [-2:2]
#set xrange [0:1]

#set ytics 2 format "%g"
#set xtics 2 format "%g"
set xlabel "{/Symbol w} [1/s]"
set ylabel "P_{n}({/Symbol w})"
set rmargin 4
#set key outside Left samplen 1 spacing 1.2 width -0.5

#set arrow nohead from -6,0 to 0,0 ls 14

plot "./PowerPlotExt_ana.dat" with lines ls 16 title "Low frequency, analytical",\
"./PowerPlotInt_ana.dat" with lines ls 19 title "High frequency, analytical",\
"./PowerPlotTot_sim.dat" with lines ls 11 title "Simulated"

set size 0.4,0.4
set origin .12,.1
#set noytic
#set noxtic
set xtic (1e-1,1e4,1e10)
set ytic (1e0,1e-10,1e-20)
set noxlabel
set noylabel
set nokey

plot "./PowerPlotExt2_ana.dat" with lines ls 16 title "Extrinsic analytical",\
"./PowerPlotInt2_ana.dat" with lines ls 19 title "Intrinsic analytical",\
"./PowerPlotTot2_sim.dat" with lines ls 11 title "Simulated"

EOF

epstopdf PowerPlot2.eps
fi






# Potentially difference between Gasper and Joris
if [[ $plot -eq 4 ]]
then

$lines1
$lines2

gnuplot << EOF -persist

set terminal postscript eps enhanced color
set out "GaspervsJoris.eps"

#$lines2

#set yrange [-2:2]
set xrange [0:1]

#set ytics 2 format "%g"
#set xtics 2 format "%g"
set xlabel "n"
set ylabel "P_{n}(0)"
set key left top

#set arrow nohead from -6,0 to 0,0 ls 14

#plot "./Results.dat"
plot "./NoisePlotJold_ana.dat" with lines ls 19 title "With cutoff",\
 "./NoisePlotJ_ana.dat" with lines ls 16 title "No cutoff"
#"./Result.dat" using 2:4 with lines notitle,\
#"./RecAverage.dat" using 2:(10*\$4):(sqrt(\$3)):(10*sqrt(\$5)) with xyerrorbars notitle

EOF

epstopdf GaspervsJoris.eps
fi






#Tableaux for saturation vs diffusive on-rate. -LE MACHINE!
if [[ $plot -eq 5 ]]
then

gnuplot << EOF -persist

$lines3

set terminal postscript eps enhanced color
set out "TableauxNoiseCmp.eps"

# x = kdD
# y = kaD
n(x,y)=(y*kaP*TF0)/(y*kdP*L + x*kdP*L**(3) + y*kaP*TF0)

kdhalf(y)=-y*(kdP*L-kaP*TF0)/(kdP*L**(3))

set key noauto

set size 1,1
set origin 0,0

set multiplot

set size .5,.5
set origin 0.,.0
set log x
set format x "10^{%L}"
set nokey
set title "b) Promoter occupancy"
set xtic (1e-2,1e0,1e2,1e4)
#set ytic (1e0,1e-10,1e-20)

set yrange [0:1]
set xrange [1e-1:1e4]

L=1e-6
TF0=10
kaP=1e-4
kdP=1e2

plot n(x,1e-10) with lines ls 1 title "10^{-10}",\
n(x,1e-11) with lines ls 2 title "10^{-11}",\
n(x,1e-12) with lines ls 3 title "10^{-12}",\
n(x,1e-13) with lines ls 4 title "10^{-13}",\
.5 with lines ls 5

set parametric

set trange[0:.5]

plot kdhalf(1e-10),t with lines ls 10,\
kdhalf(1e-11),t with lines ls 10,\
kdhalf(1e-12),t with lines ls 10,\
kdhalf(1e-13),t with lines ls 10

unset parametric

set log xy
set size .5,.5
set origin .0,.5
set format x "10^{%L}"
set format y "10^{%L}"
set nokey
set title "a) Noise - finite #TF's, with occ."
#set xtic (1e-2,1e0,1e2,1e4)
#set ytic (1e0,1e-10,1e-20)

set yrange [.75:400]
set xrange [1e-1:1e4]

plot "./NoiseCmp_10.dat" with lines ls 1 title "10^{-10}",\
 "./NoiseCmp_11.dat" with lines ls 2 title "10^{-11}",\
 "./NoiseCmp_12.dat" with lines ls 3 title "10^{-12}",\
 "./NoiseCmp_13.dat" with lines ls 4 title "10^{-13}"

set parametric

set trange[0:10]

plot kdhalf(1e-10),t with lines ls 10,\
kdhalf(1e-11),t with lines ls 10,\
kdhalf(1e-12),t with lines ls 10,\
kdhalf(1e-13),t with lines ls 10

unset parametric



set log xy
set size .5,.5
set origin .5,.0
set format x "10^{%L}"
set format y "10^{%L}"
set nokey
set title "d) Noise - infinite #TF's, no occ."
#set xtic (1e-2,1e0,1e2,1e4)
#set ytic (1e0,1e-10,1e-20)

set yrange [1e-2:500]
set xrange [1e-1:1e4]

plot "./NoisekDns_10.dat" with lines ls 1 title "10^{-10}",\
 "./NoisekDns_11.dat" with lines ls 2 title "10^{-11}",\
 "./NoisekDns_12.dat" with lines ls 3 title "10^{-12}",\
 "./NoisekDns_13.dat" with lines ls 4 title "10^{-13}"



set log xy
set size .5,.5
set origin .5,.5
set format x "10^{%L}"
set format y "10^{%L}"
set key top left
set title "c) Noise - finite #TF's, no occ."
#set xtic (1e-2,1e0,1e2,1e4)
#set ytic (1e0,1e-10,1e-20)

set yrange [3e-1:500]
set xrange [1e-1:1e4]

plot "./NoisekDs_10.dat" with lines ls 1 title "10^{-10}",\
 "./NoisekDs_11.dat" with lines ls 2 title "10^{-11}",\
 "./NoisekDs_12.dat" with lines ls 3 title "10^{-12}",\
 "./NoisekDs_13.dat" with lines ls 4 title "10^{-13}" 
#set format y "10^{%L}"
#set format x "10^{%L}"

#set yrange [-2:2]
#set xrange [0:1]

#set ytics 2 format "%g"
#set xtics 2 format "%g"
#set xlabel "{/Symbol w} [1/s]"
#set ylabel "P_{n}({/Symbol w})"
#set rmargin 4
#set key outside Left samplen 1 spacing 1.2 width -0.5

#set arrow nohead from -6,0 to 0,0 ls 14

#set size 0.4,0.4
#set origin .12,.1
#set noytic
#set noxtic
#set xtic (1e-1,1e4,1e10)
#set ytic (1e0,1e-10,1e-20)
#set noxlabel
#set noylabel
#set nokey

EOF

epstopdf TableauxNoiseCmp.eps
fi






#Pbound with a sink
if [[ $plot -eq 6 ]]
then

$lines1
$lines3

gnuplot << EOF -persist

set terminal postscript eps enhanced color
set out "SinkPbound.eps"

#$lines2

#set yrange [-2:2]
#set xrange [0:1]

n(x)=x*c/(x*c + kd)

#set ytics 2 format "%g"
#set xtics 2 format "%g"
set xlabel "k"
set ylabel "n"
set key bottom right

#set arrow nohead from -6,0 to 0,0 ls 14

set format x "10^{%L}"
set log x

c=1/1e-6
kd=1000
#plot "./Results.dat"
plot "./SinkPbound.dat" using 2:3:(sqrt(\$4)) with yerrorbar ls 7 title "Average occupancy of the sink",\
n(x) with lines ls 1 notitle

#"./SinkPbound.dat" using 2:3 with lines ls 1 notitle

EOF

epstopdf SinkPbound.eps
fi












#Survival prob in eq, ignoring time dep. rebinding.
if [[ $plot -eq 7 ]]
then

gnuplot << EOF -persist

$lines1
$lines2

set terminal postscript eps enhanced color
set out "SeqApprx.eps"

set size 1,1
set origin 0,0
#set nokey
set multiplot

set size 1,1
set origin 0,0

#set format y "10^{%L}"
#set format x "10^{%L}"

#set yrange [-2:2]
#set xrange [0:1]

#set ytics 2 format "%g"
#set xtics 2 format "%g"
set xlabel "t [s] "
set ylabel "Survival Probability"
#set rmargin 4
#set key bottom left

#set arrow nohead from -6,0 to 0,0 ls 14

plot "./SeqApprx.dat" using 1:2 with lines ls 16 title "{/Symbol G}(t|eq)",\
"./SeqApprx.dat" using 1:3 with lines ls 19 title "S(t|{/Symbol s)"

set size 0.5,0.5
set origin .4,.4
set format x "10^{%L}"
set yrange [.4:1.05]
set ytic (.4,.6,.8,1)
set xtic (1e-8,5e-7,1e-6)
set noxlabel
set noylabel
set nokey

plot "./SeqApprxInset.dat" using 1:2 with lines ls 16 title "{/Symbol G}(t|eq)",\
"./SeqApprxInset.dat" using 1:3 with lines ls 19 title "S(t|{/Symbol s})"

EOF

#latex SeqApprx.tex
#dvipdf SeqApprx.dvi
epstopdf SeqApprx.eps
fi



# 8 - Comparing rdens plots between newBD2D and GF'n 2DRadInf.
if [[ $plot -eq 8 ]]
then

gnuplot << EOF -persist

$lines1
$lines3

set terminal postscript eps enhanced color
set out "newBD2D_rdens_compare.eps"

set size 1,1
set origin 0,0
#set nokey
set multiplot

set size 1,1
set origin 0,0

set log y

set format y "10^{%L}"
#set format x "10^{%L}"

set yrange [1e5:5e10]
set xrange [1:3]

#set ytics 2 format "%g"
#set xtics 2 format "%g"
set xlabel "r/R"
set ylabel "p_{2D, rad}"
#set rmargin 4
set key top left

#set arrow nohead from -6,0 to 0,0 ls 14

plot "./newBD2D_rdenssim_1.dat" with points pt 1 ps 2 title "t_{sim} = 10^{-1} {/Symbol t}",\
"./newBD2D_rdenssim_2.dat" with points pt 4 ps 2 title "t_{sim} = 10^{-2} {/Symbol t}",\
"./newBD2D_rdenssim_3.dat" with points pt 6 ps 2 title "t_{sim} = 10^{-3} {/Symbol t}",\
"./newBD2D_rdenssim_4.dat" with points pt 10 ps 2 title "t_{sim} = 10^{-4} {/Symbol t}",\
"./newBD2D_rdensana_1.dat" with lines ls 1 notitle,\
"./newBD2D_rdensana_2.dat" with lines ls 2 notitle,\
"./newBD2D_rdensana_3.dat" with lines ls 3 notitle,\
"./newBD2D_rdensana_4.dat" with lines ls 4 notitle

set nolog y
set size 0.5,0.5
set origin .47,.47
set format y "10^{%L}"
set yrange [0:1e8]
set xrange [1:3]
set ytic (1e8,1e7)
set xtic (1,1.5,2,2.5,3)
#set xlabel "r/R" font "CMBX10, 10"
#set ylabel "p_{irr}" font "CMBX10, 10"
set key top right

plot "./newBD2D_rdensana_1.dat" with lines ls 1 title "t_{sim} = 10^{-1} {/Symbol t}",\
"./newBD2D_rdenssim_1.dat" with points pt 4 ps 1 title "{/Symbol D} t = 10^{-5} {/Symbol t}",\
"./newBD2D_rdenssim_1b.dat" with points pt 1 ps 1 title "{/Symbol D} t = 10^{-4} {/Symbol t}",\
"./newBD2D_rdenssim_1c.dat" with points pt 3 ps 1 title "{/Symbol D} t = 10^{-3} {/Symbol t}"


EOF

epstopdf newBD2D_rdens_compare.eps
fi
